stages:
    - test
    - mirror
    - cleanup

test:
    stage: test
    script:
        - export COMPOSE_FILE=docker-compose.ci.yml
        - make ${COMPOSE_FILE} test

mirror:
    stage: mirror
    script:
        - "curl -X POST --fail -F token=${MIRROR_TOKEN} -F ref=master -F variables\\[REPO\\]=hanaboso-go-log https://gitlab.hanaboso.net/api/v4/projects/131/trigger/pipeline"
    only:
        - master

cleanup:
    stage: cleanup
    when: always
    script:
        - export COMPOSE_FILE=docker-compose.ci.yml
        - make ${COMPOSE_FILE} docker-down-clean || echo "CleanUP failed"
