version: '3.5'

services:
  app:
    image: hanabosocom/go-base:1.19
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/app
      - ${GOPATH}/pkg:/go/pkg
    environment:
      DEV_UID: ${DEV_UID}
      DEV_GID: ${DEV_GID}
